### ISSUE TITLE
@nrwl/nx support

### ISSUE THREAD

**Issue by FallenRiteMonk** [brechtbilliet/ngrx-undo#14]
I'm using @nrwl/nx in my project for ngrx integration. I would also like to use this lib for optimistic updates, but following [the nx way](https://nrwl.io/nx/guide-data-persistence) of doing them, its not possible to use this lib, due to the way the actions are compared.

This is my effect method:
```
@Effect()
  editIngredients = this.d.optimisticUpdate('EDIT_INGREDIENT', {
    run: (a: EditIngredient, state: MasterDataState) => {
      const action = { type: 'INGREDIENT_EDITED', payload: a.payload };
      this.apiService.editIngredient(a.payload.ingredient);
      return action;
    },

    undoAction: (a: EditIngredient, e: any) => {
      const action = { type: 'INGREDIENT_EDITED', payload: a.payload };
      return (undo(action));
    }
  });
```

This does not work because the action I pass to the undo method is not the same as the one fired in the run method, because in the lib actions are compared using '!==' operator during filtering.
I just quickly tested, but comparing the actions using '!Object.is()' method would solve the problem.

Would this fix have any other effects to the lib?

If not, I'd be happy to make a PR.

**Comment by SamVerschueren** [comment]
You probably wrote the `optimisticUpdate` function? I would suggest passing  the initial action to the undo method. Checking the references of the objects is the only reliable way of knowing which action should be undone. For instance, what would happen if you dispatch the same action type with the same payload twice? Without reference check, you can't reliably know which action you mean.

**Comment by FallenRiteMonk** [comment]
No I didn't write the ```optimiticUpdate``` function, it's part of ```@nrwl/nx```, that's the problem, but you are right. I'll try opening a issue at the repo of ```@nrwl/nx```.
