### ISSUE TITLE
Stores occasionally restart

### ISSUE THREAD

**Issue by gergely-kovacs** [brechtbilliet/ngrx-undo#17]
We ran into an issue where the first element in the array of executed actions (*firstAction*) was `@ngrx/store/update-reducers`, thus `rootReducer(initialState, firstAction);` was causing the stores to reset to their initial state.

I've written a fix for it, and i'll submit a pull request, please take a look at it!
Thanks in advance!

Edit:
It was caused by some strange interaction with another meta-reducer, yet I think it's not necessary to store the init and update actions.
Changing their order in the metaReducers array solved our problem.

i.e.:
`[handleUndo, localStorageSyncReducer] // buggy`  
`[localStorageSyncReducer, handleUndo] // working`

**Comment by Fellach** [comment]
OMG @brechtbilliet,

the same situation is with my custom debug meta reducer. The order in
```js
export const metaReducers: MetaReducer<State>[] = [
  handleUndo,
  debug,
];

export function debug(reducer: ActionReducer<any>): ActionReducer<any> {
  return function(state, action) {
      console.log('- action:', action, '- state:', state);
    return reducer(state, action);
  };
}
```
causes that the effects (`@ngrx/effects/init`) was re-initialized and all actions doubled. The moment of it was when reached the buffer's limit.
