### ISSUE TITLE
Undo breaks state if lazy loading reducers

### ISSUE THREAD

**Issue by shayded-exe** [brechtbilliet/ngrx-undo#20]
When ngrx lazy loads a reducer, the meta reducers are re-created. This breaks the undo reducer because it locally stores the initial state and executed actions. When undoing an action in this situation, any actions executed before the last reducer was loaded will be lost.

initialState and executedActions should be stored outside the meta reducers so they don't get reset.

**Comment by hazmah0** [comment]
I actually forked this project to fix this exact problem before my vacation on August 1, 2018 https://github.com/hazmah0/ngrx-undo.

Now that I'm back again, I've submitted a PR for this just now which you can find here:
https://github.com/brechtbilliet/ngrx-undo/pull/21

**Comment by jaichandra** [comment]
Perfect :) I had been debugging an issue with my state for last couple of hours and noticed the same. Came here to log an issue and I see this. The PR should be merged. I'll meanwhile point to the fork and test.

**Comment by brechtbilliet** [comment]
Sorry for the delay, I'll take a look at this asap!

**Comment by hazmah0** [comment]
Any chance for a new release with this fix included? 😅

**Comment by brechtbilliet** [comment]
Done, srr for the delay
