### ISSUE TITLE
Upgrade to be compatible with rxjs 6+

### ISSUE THREAD

**Issue by madcapper2** [brechtbilliet/ngrx-undo#22]
To upgrade to Angular 7, I get an error that ngrx-undo has a peer dependency on rxjs ^5.1.0 and it won't allow the upgrade.  Could this library update its dependency to rxjs 6+?

**Comment by brechtbilliet** [comment]
Sure, I'll do that this evening

**Comment by madcapper2** [comment]
Thanks for the quick update
