### ISSUE TITLE
How to use undo dispatch with interfaced actions / classes?

### ISSUE THREAD

**Issue by zmnv** [brechtbilliet/ngrx-undo#23]
Hello!
How to use `store.dispatch(undo(action));` with that model?

```Property 'type' is missing in type 'typeof UpdateObject' but required in type 'Action'.```

![image](https://user-images.githubusercontent.com/25253501/50724792-9bfcaa00-1125-11e9-9f3d-e67bc3102fea.png)

---

![image](https://user-images.githubusercontent.com/25253501/50724590-baad7180-1122-11e9-9724-f88a80e10673.png)

**Comment by zmnv** [comment]
just tryed:
![image](https://user-images.githubusercontent.com/25253501/50727360-76cf6200-114c-11e9-92fd-5562c3025d88.png)

is it good solution? 

But now, undo(action) works like RESET (reset all changes to 'initial' state when page loaded, skip middle UpdateObject actions), not like UNDO 1 action event back. Is it normal?

**Comment by zmnv** [comment]
okay.... i need to understand why UNDO calls that...

I've made 6 changes and press button with `undo()`. Go to console:

![image](https://user-images.githubusercontent.com/25253501/50727579-74bad280-114f-11e9-9297-412feeae3809.png)

(red text – changes of state in steps)

That's why UNDO works like RESET. Hm....

**Comment by brechtbilliet** [comment]
You need to undo an action, not a type of an action
