### ISSUE TITLE
Add an action creator

### ISSUE THREAD

**Issue by SamVerschueren** [brechtbilliet/ngrx-undo#5]
Just wondering if you want something like this in `ngrx-undo`, no problem if not. But I believe it's best practice to work with action creators when working with Redux which will create the desired action object for you. It could be added to `ngrx-undo` as well in, for example, the following form.

```ts
import { undo } from 'ngrx-undo';

store.dispatch(action);
store.dispatch(undo(action));
```

instead of

```ts
import { UNDO_ACTION } from 'ngrx-undo';

store.dispatch(action);
store.dispatch({type: UNDO_ACTION, payload: action});
```

Let me know what you think, happy to do a PR.

**Comment by brechtbilliet** [comment]
Sounds like a great plan Sam! Your PR would be most welcome! Thanks for being involved!

**Comment by SamVerschueren** [comment]
> Thanks for being involved!

I love the project, I use it in every angular 2 app where I use redux so glad I can give something in return ;).

**Comment by zmnv** [comment]
how to use `store.dispatch(undo(action));` with that model?

![image](https://user-images.githubusercontent.com/25253501/50724582-9b164900-1122-11e9-8225-0c4b87baf839.png)


![image](https://user-images.githubusercontent.com/25253501/50724590-baad7180-1122-11e9-9724-f88a80e10673.png)
