### ISSUE TITLE
Doesnt work with @ngrx/store v4

### ISSUE THREAD

**Issue by ezequielzacca** [brechtbilliet/ngrx-undo#9]
Please could you upgrade for ngrx v4?

**Comment by zamber** [comment]
WFM. Care to elaborate what breaks?

**Comment by acip** [comment]
@zamber here are the erors:

`ERROR in <LOCAL_PATH>/node_modules/ngrx-undo/src/storeUndo.d.ts (1,10): Module '"<LOCAL_PATH>/node_modules/@ngrx/store/store"' has no exported member 'Reducer'.`

`ERROR in <LOCAL_PATH>/node_modules/ngrx-undo/src/storeUndo.d.ts (1,19): Module '"<LOCAL_PATH>/node_modules/@ngrx/store/store"' has no exported member 'Dispatcher'.`

**Comment by zamber** [comment]
You're importing members wrong. Sample error I generated: 

    .../connectivity.reducer.ts (1,42): Module '".../node_modules/@ngrx/store/index"' has no exported member 'Dispatchere'.

this is for:

    import { Dispatchere } from '@ngrx/store';

It looks like a version mismatch but double-check if the imports are OK (VS Code has extensions that can do that for you).

As for the versions I'm using:

    "@ngrx/store": "2.2.3",
    "@ngrx/store-devtools": "3.2.4",
    "ngrx-undo": "^2.0.0",

**Comment by ezequielzacca** [comment]
@zamber yes but that is not v4 of ngrx store

**Comment by brechtbilliet** [comment]
I'm working on a solution, the api from v2 is completely different then v4. 
That's why I might create an easier solution that doesn't involve an angular module and use the metareducers property

**Comment by ezequielzacca** [comment]
thank you, the feature ngrx undo provides is really usefull and i think is a must for every production app

**Comment by brechtbilliet** [comment]
I have updated the version to 4.0.1. There are breaking changes on how to use the module. It did got simpler though... https://www.npmjs.com/package/ngrx-undo
